modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-3.0"
[[mods]]
modId="additionaladditions"
version="3.0.1"
displayName="Additional Additions"
logoFile="icon.png"
authors="Dqu1J"
description='''
  Additional Additions is a mod that aims to add additional uses for Copper, Amethyst and Glow Ink Sacs as well as other useful additional additions to the game.
'''

[[dependencies.additionaladditions]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionaladditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
