modLoader="javafml"
loaderVersion="[40,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/Additional-Mods/additionaladditions"
[[mods]]
modId="additionaladditions"
version="6.0.2"
displayName="Additional Additions"
logoFile="icon.png"
authors="Dqu1J"
credits="MorganFreeguy | MF#1861, adoghr, Avila27, aresociety, wdnmdyaya, zrll12, ChromexUnderscore, DerTwitchLappen, Mira047, Darkhax, Fuzss, Emafire003, JustFoxx, foul-fortune-feline, houlstycraft, Alyson, baooduy, nzuliaf, Grape reprint"
description='''
  Additional Additions is a mod that aims to add additional uses for Copper, Amethyst and Glow Ink Sacs as well as other useful additional additions to the game.
'''

[[dependencies.additionaladditions]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionaladditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"
